apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: argocd-override-integration-server-image
spec:
  params:
    - name: flags
      default: --
    - name: argocd-version
      default: v2.2.5
  resources:
    inputs:
      - name: source
        type: git
  stepTemplate:
    envFrom:
      - secretRef:
          name: argocd-env-secret  # used for server and authentication (username/password or auth token)
  steps:
    - name: argocd-app-sync
      image: argoproj/argocd:$(params.argocd-version)
      script: |
        repo=$(echo "$(resources.inputs.source.url)" | sed -n "s/https:\/\/[^\/]*\/\([^/.]*\)\/\([^/.]*\)\(.git\)\?/\2/p")
        echo "Repo is $(repo) which will be used as application name"
        argocd login $ARGOCD_SERVER --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD
        argocd app set $(repo) -p image.tag=$(resources.inputs.source.revision)
        argocd app sync $(repo) $(params.flags)
        argocd app wait $(repo) --health $(params.flags)
