apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: argocd-override-parameter
spec:
  params:
    - name: flags
      default: --
    - name: argocd-version
      default: v2.2.5
    - name: param
      description: the parameter that should be overridden
    - name: gitrepo
    - name: gitrevision
  stepTemplate:
    envFrom:
      - secretRef:
          name: argocd-env-secret  # used for server and authentication (username/password or auth token)
  steps:
    - name: argocd-app-sync
      image: argoproj/argocd:$(params.argocd-version)
      script: |
        repo=$(echo "$(params.gitrepo)" | sed -n "s/https:\/\/[^\/]*\/\([^/.]*\)\/\([^/.]*\)\(.git\)\?/\2/p")
        echo "Repo is $repo which will be used as application name"
        argocd login --insecure $ARGOCD_SERVER --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD
        argocd app set $repo -p $(params.param)=$(params.gitrevision)
        argocd app sync $repo $(params.flags)
        argocd app wait $repo --health $(params.flags)
