apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-s2i-ace-maven
  namespace: my-namespace
spec:
  resources:
    - name: source
      type: git
    - name: image
      type: image
  tasks:
    - name: buildah-pr
      params:
        - name: BUILDER_IMAGE
          value: 'registry.redhat.io/rhel8/buildah:8.3'
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'false'
        - name: FORMAT
          value: oci
      resources:
        inputs:
          - name: source
            resource: source
        outputs:
          - name: image
            resource: image
      taskRef:
        kind: ClusterTask
        name: buildah-pr
