apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tag-image-with-latest
spec:
  description: >-
    Tags the image resource with the latest tag if not using the latest tag
    already.
  params:
    - default: >-
        registry.redhat.io/rhel8/buildah@sha256:180c4d9849b6ab0e5465d30d4f3a77765cf0d852ca1cb1efb59d6e8c9f90d467
      description: The location of the buildah builder image.
      name: BUILDER_IMAGE
      type: string
    - default: 'true'
      description: >-
        Verify the TLS on the registry endpoint (for push/pull to a non-TLS
        registry)
      name: TLSVERIFY
      type: string
  resources:
    inputs:
      - name: image
        type: image
  steps:
    - image: $(params.BUILDER_IMAGE)
      name: tag-image
      resources: {}
      script: |
        #!/usr/bin/env bash
        regex="(.+\/[^:]+):?(.+)?"
        if [[ "$(resources.inputs.image.url)" =~ $regex ]]
        then
          echo "Tagging and pushing $(resources.inputs.image.url) as ${BASH_REMATCH[1]}:latest"

          buildah tag $(resources.inputs.image.url) ${BASH_REMATCH[1]}:latest
          buildah push --tls-verify=$(params.TLSVERIFY) ${BASH_REMATCH[1]}:latest docker://${BASH_REMATCH[1]}:latest
        else
          echo "Unable to capture image from URL $(resources.inputs.image.url)"
          exit 1
        fi
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
  volumes:
    - name: varlibcontainers
      persistentVolumeClaim:
        claimName: s2i-ace-maven-varlibcontainers-pvc
