apiVersion: v1
kind: Template
parameters:
  - name: CONFIGURATION_NAME
    required: true
  - name: CONFIGURATION_NAMESPACE
    required: true
  - name: DATA
    required: true
    description: The content as base64
  - name: CONFIGURATION_TYPE
    required: true
    description: The type of the configuration
metadata:
 name: configuration-template
objects:
  - apiVersion: appconnect.ibm.com/v1beta1
    kind: Configuration
    metadata:
      name: ${CONFIGURATION_NAME}
      namespace: ${CONFIGURATION_NAMESPACE}
    spec:
      contents: >-
        ${{DATA}}
      type: ${CONFIGURATION_TYPE}
