apiVersion: v1
kind: Template
parameters:
  - name: CONFIGURATION_NAME
    required: true
  - name: CONFIGURATION_NAMESPACE
    required: true
  - name: DATA
    required: true
    description: The server.conf.yml content as base64
metadata:
 name: configuration-serverconf-template
objects:
  - apiVersion: appconnect.ibm.com/v1beta1
    kind: Configuration
    metadata:
      name: ${CONFIGURATION_NAME}
      namespace: ${CONFIGURATION_NAMESPACE}
    spec:
      contents: >-
        ${{DATA}}
      type: serverconf
