apiVersion: v1
kind: Template
parameters:
  - name: INTEGRATION_SERVER_NAME
    required: true
  - name: INTEGRATION_SERVER_NAMESPACE
    required: true
  - name: IS_IMAGE
    required: true
  - name: LICENSE
    value: L-APEH-BY5CY7
  - name: LICENSE_USE
    value: CloudPakForIntegrationProduction
  - name: LICENSE_ACCEPT
    required: true
metadata:
 name: integration-server-template
objects:
  - apiVersion: appconnect.ibm.com/v1beta1
    kind: IntegrationServer
    metadata:
      name: ${INTEGRATION_SERVER_NAME}
      namespace: ${INTEGRATION_SERVER_NAMESPACE}
    spec:
      adminServerSecure: true
      designerFlowsOperationMode: disabled
      license:
        accept: ${{LICENSE_ACCEPT}}
        license: ${LICENSE}
        use: ${LICENSE_USE}
      pod:
        containers:
          runtime:
            image: ${IS_IMAGE}
            resources:
              limits:
                cpu: 300m
                memory: 350Mi
              requests:
                cpu: 300m
                memory: 300Mi
      replicas: 1
      router:
        timeout: 120s
      service:
        endpointType: http
      version: 11.0.0.11-r2
